project:
  type: website
  output-dir: docs

website:
  title: "Eva Shaw"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/Emoiraine/emoiraine.github.io
format:
  html:
    theme: cosmo
    css: styles.css



